### ISSUE TITLE
Multiple Markers in geojson

### ISSUE THREAD

**Issue by nurseymybush** [perliedman/leaflet-realtime#10]
So my issue is that I am trying to load multiple markers from a json file formatted to geojson but only the first marker ever shows up on the map.

Example of file:
```javascript
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "Name": "Worker1",
		"Status": "break"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -112.7171529,
          33.4954179
        ]
      }
    },
	{
      "type": "Feature",
      "properties": {
        "Name": "Worker2",
		"Status": "work"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -115.7171529,
          32.4954179
        ]
      }
	}
  ]
}
```
example of js:
```javascript
realtime = L.realtime({
		  url: 'myaddress/locations.json',
	      crossOrigin: true,
	      type: 'json'
	  }, {
	      interval: 5 * 1000,
	      onEachFeature: function(feature, layer) {
	    	  var content = '<h3>Serviceperson<\/h3>' +
	          '<p>Name: ' + feature.properties.Name + '<br \/>' +
	          'Status: ' + feature.properties.Status + '<\/p>';    	  
	    	  layer.bindPopup(content);
	      }
	    });
var overlayMaps = { 
"Drivers": realtime
};
	  var layerControl = L.control.layers(null, overlayMaps, {collapsed: false }).addTo(map);
```

**Comment by perliedman** [comment]
Hi there, please see the second paragraph in [the overview](https://github.com/perliedman/leaflet-realtime#overview):

>To be able to figure out when new features are added, when old features are removed, and which features are just updated, Leaflet Realtime needs to identify each feature uniquely. This is done using a feature id. Usually, this can be done using one of the feature's properties. By default, Leaflet Realtime will try to look for a called property id and use that.

You can set a custom function to get a feature's identifier with the `getFeatureId` [option](https://github.com/perliedman/leaflet-realtime#-options).

**Comment by nurseymybush** [comment]
Thanks for your help! I got it working now.

**Comment by DatanoiseTV** [comment]
@nurseymybush Can you share your solution? Thank you!

**Comment by perliedman** [comment]
@DatanoiseTV it comes down to that each of your features must include a unique property to identify it, and is able to tell which feature is which in each request.

This can be anything inside your feature. Lets say you have a property called `myUniqueIdentifier` within the feature's `properties`. You would then have to explain to Leaflet Realtime how to access this property. You do this by specifying the `getFeatureId` option:

```
var realtime = L.realtime({ ... request configuration ... }, {
    getFeatureId: function(feature) { return feature.properties.myUniqueIdentifier; }
});
```

This means that Leaflet Realtime will call your `getFeatureId` function for each feature, and it will return the feature's identifier that you've chosen.

If you don't provide your own `getFeatureId`, Leaflet Realtime will assume there's an identifier in each feature's `properties.id` and use that. If you do this, but don't have such an identifier in the actual features, all feature will get the same id, `undefined`, which is rarely what you want.

**Comment by nurseymybush** [comment]
@DatanoiseTV I'll try to find the code I wrote

**Comment by axelgunn** [comment]
hi there

Is there a way to persist every real-time marker ever drawn on a map until I clear my layer. Even though he is not always part of the regular interval GeoJson set used to update the map?

Thanks
Axel

**Comment by perliedman** [comment]
@axelgunn if you hook up to the `update` event, you can do any kind of persistence you like.
