### ISSUE TITLE
how to use mobile phone's gps data

### ISSUE THREAD

**Issue by riddle911** [perliedman/leaflet-realtime#102]
Hi,
I am writing an android app using leaflet .
I tried to using a market on the map which updates its coordinates by phone's gps data.
I noticed that you suggest using function(success,err) I tried but failed.

Here is my code.
````
var posdata = {
				"geometry": {
					"type": "Point",
					"coordinates": []}, 
				"type": "Feature",
				"properties": {}
		 	};

realtime = L.realtime(function(success,error){
		plus.geolocation.watchPosition(function(pos){//this function gives the coordinates of the phone like this(50,5)
	        var lon = pos.coords.longitude;
	        var la = pos.coords.latitude;
	//here I don't know how to make it work .....
       		
		 	console.log(posdata);});
		}, {
			 interval:250	        	       
		}).addTo(mymap);

````

Can you help me with this ...I am new to coding, and cannot solve this.

**Comment by perliedman** [comment]
Hi,
here's a slightly modified version of your example, that works for me:

https://plnkr.co/edit/F2XUAffqnDlyyBR379a1?p=preview

Hope this helps!

**Comment by riddle911** [comment]
Many thanks! It's very kind of you.
I tried and it works.
