### ISSUE TITLE
geojson properties not taken into account

### ISSUE THREAD

**Issue by niamiot** [perliedman/leaflet-realtime#103]
Hi,

I've an issue when I try to display information from a geojson file to a map.
The properties of my geojson features are not taken into account. 

Typically the following json file doesn't display a green triangle when I load it from an url, whereas it is correctly display in [geojson.io](http://bl.ocks.org/d/65afa8903f116b9c04fb54df079ae429)

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id":1,
        "fill": "#00FF00",
        "fill-opacity": 0.5
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -75.289306640625,
              40.13899044275822
            ],
            [
              -75.5255126953125,
              40.000267972646796
            ],
            [
              -75.29754638671875,
              39.86969567045658
            ],
            [
              -75.289306640625,
              40.13899044275822
            ]
          ]
        ]
      }
    }
  ]
}
```
Am I doing something wrong ?

**Comment by perliedman** [comment]
Hi there!

The styling information you provide in the properties in an extension that `geojson.io` use, but it's not part of the GeoJSON standard, neither is it supported by Leaflet. I _think_ it's the [simplestyle-spec](https://github.com/mapbox/simplestyle-spec), but I'm not sure.

I think there might be a Leaflet plugin to support it, but I'm far from sure if you can make it work with Leaflet Realtime.

If you have any success with something like this, feel free to tell us here for sake of future documentation! Also, help with improving Leaflet Realtime to make this easier is always welcome.
