### ISSUE TITLE
Update individual marker icons based on conditions

### ISSUE THREAD

**Issue by Kbman99** [perliedman/leaflet-realtime#107]
Hello,
So I've been working through this issue for a while and have looked through all the issues already closed such as https://github.com/perliedman/leaflet-realtime/issues/60 as well as on stackoverflow. Though since this commit here https://github.com/perliedman/leaflet-realtime/commit/a1205598cd38675161687c9aac278ea034412501#diff-4a0fd53fbba17792254194cc6d6e6601 the updateFeature function has been modified to now only take in `feature` and `oldLayer` as arguments and most examples use the old version of the function. 

My problem is that I have a bunch of markers on my map and I would like to update their icons individually based on a value within the feature. I've gotten to the point where I can change the icons for each marker using `pointToLayer` at the very start, however I cannot figure out for the life of me how I can take an individual marker and change its icon on every update.

Every time I run the code I get an issue where `oldLayer` is undefined within `updateFeature`. I'm sure it's possible I'm missing something super simple, but is it the case that updating the icon updates every icon on the GEOJson layer or that I need to be using layer group?

Here is my current code just for testing it generates random values-

```
                var mymap = L.map('map', {center: [35.0545, -95.28], zoom: 4}),
                    realtime = L.realtime({
                        url: "{{ url_for('api.get_data', id=current_user.id) }}",
                        crossOrigin: true,
                        type: 'json'
                    }, {
                        interval: 5 * 1000,
                        pointToLayer: function (feature, latlng) {
                            var rand = Math.floor((Math.random() * 100) + 1);
                            console.log(rand);
                            if (rand >= 50) {
                                marker = L.marker(latlng, {icon: red});
                            }
                            else {
                                marker = L.marker(latlng, {icon: orange});
                            }

                            return marker;
                        },
                        updateFeature: function(f, oldLayer) {
                            var rand = Math.floor((Math.random() * 100) + 1);
                            console.log(rand);
                            if (rand >= 50) {
                                oldLayer.setIcon(orange);
                            }
                            else {
                                oldLayer.setIcon(red);
                            }
                            return L.Realtime.prototype.options.updateFeature(f, oldLayer);
                        },
                        getFeatureId: function (f) {
                            return f.properties.node_id;
                        },
                        onEachFeature: function (f, l) {
                            l.bindPopup(function () {
                                //console.log(f);
                                return '<h3>' + f.properties.node_id + '</h3>' +
                                    '<div class="ui divider"></div>' +
                                    '<p> <b> Current Location: </b>' + node_dict[f.properties.node_id]
                                        .coords[node_dict[f.properties.node_id].coords.length - 1] + '</p>' +
                                    '<p> <b> Last Update: </b>' + node_dict[f.properties.node_id]
                                        .lastUpdate[node_dict[f.properties.node_id].lastUpdate.length - 1] + '</p>'
                            });
                        }
                    }).addTo(mymap);
```

Any help is greatly appreciated!
Thanks

**Comment by perliedman** [comment]
Without digging deep into your code, I'd start with adding a simple check to the top of your `updateFeature` function:

```js
                        updateFeature: function(f, oldLayer) {
                            if (!oldLayer) { return; }
                            var rand = Math.floor((Math.random() * 100) + 1);
                            ...
```

**Comment by Kbman99** [comment]
Awesome, it works with the code below!
```
updateFeature: function(f, oldLayer) {
    if (!oldLayer){ return; }

    var rand = Math.floor((Math.random() * 100) + 1);

    if (rand >= 50) {
        oldLayer.setIcon(orange);
    }
    else {
        oldLayer.setIcon(red);
    }
}
```
 I figured it would be simple, I just didn't understand what exactly `oldLayer` was. I'm guessing what was happening was as you had mentioned elsewhere, that when there is nothing to update (such as at the very beginning before markers are placed) `oldLayer` simply isn't defined because it has not been created. So adding the check was all I needed. Thanks again for your help. Should another issue arise I will reopen this issue.

**Comment by Kbman99** [comment]
So I'm reopening this issue because I've hit another wall. Everything was working fine and now what seems to happen is the new marker gets added, but is removed. You can't see the new marker get added, but in the debugger I can see that the new marker gets added and then this line of code is hit here @Line 194 

```
            layer.feature = f;
            if (container.resetStyle) {
                container.resetStyle(layer);
            }

            if (oldLayer) {
                update[fId] = geojson;
                if (oldLayer != layer) {
                    layersToRemove.push(oldLayer);
                    container.addLayer(layer);
                }
            } else {
                enter[fId] = geojson;
                container.addLayer(layer);
            }

            this._featureLayers[fId] = layer;
            this._features[fId] = seenFeatures[fId] = f;
```

After this code runs, the original marker is added back to the map (along with the new marker that should be there)
It looks like this https://i.imgur.com/6dBcvU1.png

Then this code runs @Line 219 in leaflet-realtime.js

```
        for (i = 0; i < layersToRemove.length; i++) {
            this._container.removeLayer(layersToRemove[i]);
        }
```
Once this runs, the newly added markers (which I want to be on the map) get removed.

I have been looking for a while and will continue to, but I can't seem to find a reason as to why this is happening.

**Comment by perliedman** [comment]
It looks like the return value from `updateLayer` is missing.

If `updateLayer` returns a falsy value (`null`, `undefined`, `false`, `0`, etc.), Leaflet Realtime will interpret it as if updating the layer was not possible, and it will create a new layer instead, replacing the old layer.

So, you could probably just add `return oldLayer;` as the last line of the function.

**Comment by Kbman99** [comment]
@perliedman It seems that you're solution works, but not entirely. By doing as you suggest, the marker itself is updated to the correct color/new marker, however the position of the marker is not updated properly so it remains in the same spot.

removing `return oldLayer;` fixes the position update, but the same issue with the icon not changing happens.

**Comment by Kbman99** [comment]
Okay so after getting home from work, I decided to do a bit more debugging and when I remove the `updateFeature()` option on the `L.realtime` object everything worked, but just no icon change. Once I went through the I saw the default `updateFeature()` function runs and uses the `oldLayer.setLatLng(lng, lat)` before `return oldLayer;`. So all I did, was at the top of the `updateFeature()` option, I added the necessary lines and it works!

For anyone in the future who may want to do this, the code below shall serve as an example. @perliedman can comment as to whether this is necessary so I will let him close this issue if he thinks it's a good solution.

Thanks for all the help.

```
// Setup the icons to change to based on whatever condition you need

var red = L.icon({
    iconUrl: 'http://leafletjs.com/examples/custom-icons/leaf-red.png',
    iconSize: [30, 30]
});

var green = L.icon({
    iconUrl: 'http://leafletjs.com/examples/custom-icons/leaf-orange.png',
    iconSize: [30, 30]
});

updateFeature: function(f, oldLayer) {
    if (!oldLayer){ return; }

    var c = f.geometry.coordinates;
    oldLayer.setLatLng([c[1], c[0]]);

    var rand = Math.floor((Math.random() * 100) + 1);

    if (rand >= 50) {
        oldLayer.setIcon(green);
    }
    else {
        oldLayer.setIcon(red);
    }

    return oldLayer;
}
```

**Comment by perliedman** [comment]
Hm, yes, `updateFeature` needs to do _all_ updates on the layer, LRM in itself assumes this is what the function does, and will not automatically call `setLatLng` or similar (that's why the default implementation of `updateFeature` does exactly that).

So, it looks like you're good - I'm closing this issue for now?

**Comment by akaivola** [comment]
For those finding this issue later I want to document the actual behaviour of this very vital function.

If you want to programmatically change a marker position, color or rotation when leaflet realtime receives new data, updateFeature works actually as follows:

```updateFeature(feature marker) {
 // feature = updated js object of your feature data
 // marker = leaflet marker object
}```
