### ISSUE TITLE
Local gps input without using geoJSON

### ISSUE THREAD

**Issue by dev-brother** [perliedman/leaflet-realtime#11]
Hi perliedman

In the examples folder of leaflet-realtime, the file "index.js" starts out as:
```
var map = L.map('map'),
    realtime = L.realtime({
        url: 'https://wanderdrone.appspot.com/',
        crossOrigin: true,
        type: 'json'
    }, {
        interval: 3 * 1000
    }).addTo(map);
```
How do we use local data where gps is already stored as php variables? Currently the example points to Wanderdrone, but doesn't explain how the geoJSON string is built on the sending side.

I have php variables for lat and lon stored on my server, and all I need is to pass them to L.realtime. I am not good with js, so could use a bit of help. Perhaps you could add another function
to handle local php variables akin to...

```
var map = L.map('map'),
    realtime = L.realtime({
        url: 'localhost/gps.php',
        type: 'php'
    }, {
        interval: 3 * 1000
    }).addTo(map);
```
Where gps.php retrieves the values of $lat and $lon. 

or could you provide an example how to build a simple php page to serve a geoJSON string, similar to the output from Wanderdrone.

```
{"geometry": {"type": "Point", "coordinates": [92.838612769265353, 11.693297684792899]}, "type": "Feature", "properties": {}}
```

Regards

Lee

**Comment by swordsteel** [comment]
Here is a home brew wanderdrone, but alas not working. If i visit wanderdone my geoJSON string is exactly the same.

```
<?php
//include_once('geoPHP/geoPHP.inc');


$lat = mt_rand(0,90) + abs(1-mt_rand()/mt_rand()) ;

$lon = mt_rand(0,90) + abs(1-mt_rand()/mt_rand()) ;

echo $json = '{"geometry": {"type": "Point", "coordinates": [' . $lat . ', ' . $lon . ']}, "type": "Feature", "properties": {}}';
?>
```

So basically in index.js I replace the line...

```
url: 'https://wanderdrone.appspot.com/',
```
with
```
url: 'http://<myurl.com>/gps/geo.php',
```
visting the two urls in a browser we get;

wanderdrone
```
{"geometry": {"type": "Point", "coordinates": [16.310495934491744, 48.817634321648569]}, "type": "Feature", "properties": {}}
```
then gps.php
```
{"geometry": {"type": "Point", "coordinates": [57.4069200555, 57.688648988729]}, "type": "Feature", "properties": {}}
```
coupla digits short in the coords but the syntax is spot on.

btw, are you still developing L.realtime?

**Comment by perliedman** [comment]
That should work. Could you describe what errors you're encountering? Open the developer tools in your browsers and check the console for logs, etc.

Leaflet Realtime definitely works with data sent from PHP, I use it in production with a PHP backend, no need for any special treatment for this in the plugin.

Just guessing here, but might it be that the server delivering the GeoJSON (from your PHP) is some other than where you host the JavaScript? Browsers prevent this unless the server sets the `access-control-allow-origin` HTTP header.

Regarding your question about developing the plugin, as I mentioned I'm using it in production for a customer, so I'm certainly maintaining it, but there's no active development going on, since it currently covers my use cases.

**Comment by swordsteel** [comment]
Okay, here is how I got this working.

I created a geo.json file on my server that gets rebuilt by a call geo.php. Basically it's a quick and dirty wanderdone without the front end. The gps coords generated by geo.php will randomize either globally or around a local $lat and $lon. This is useful when you want to zoom in and see smaller steps  between gps jumps in L.reatlime. 

```
//geo.php - quick and dirty solution
<?php

//page refresh set by content="<some number in seconds>"
echo '<meta http-equiv="refresh" content="6" />';

//make drone randomize around specific location
//$lathere = 22;
//$lonhere = 12;

//swap these lines to make drone randomize around a specific location
$lat = mt_rand(0,90) + abs(1-mt_rand()/mt_rand()) ;
//$lat = $lathere + (abs(1-mt_rand()/mt_rand())) ;

//swap these lines to make drone randomize around a specific location
$lon = mt_rand(0,90) + abs(1-mt_rand()/mt_rand()) ;
//$lon = $lonhere + (abs(1-mt_rand()/mt_rand())) ;

//the meat and cake for the geo.json format
echo $file =  '{'  . PHP_EOL .  '"geometry" : {'  . PHP_EOL .  '"type" : "Point",'  . PHP_EOL .  '"coordinates" : [' . $lon . ',' . $lat .  ']'  . PHP_EOL .  '},'  . PHP_EOL .  ' "type" : "Feature",'  . PHP_EOL .  ' "properties" : {}'  . PHP_EOL .  '}';

$jsonfile = fopen("geo.json", "w")  or die ("Unable to open file!");
fwrite($jsonfile, $file);
fclose($jsonfile);
?>
```
This outputs a properly formatted geo.json file to the server. For dev its fine, but needs to be called by an open browser. Would be nice if this was an automatic script that didn't need a browser to call it.

The output contents for geo.json looks like this...
```
{
"geometry" : {
"type" : "Point",
"coordinates" : [12.748978719148,22.507198837402]
},
"type" : "Feature",
"properties" : {}
}
```
So all left to do is point index.js in L.reatlime to
```
url: 'http://<whatever-url>/geo.json'
```
and L.realtime does its thing, and voila your own wanderdrone, aka L.drone. 

Can you give examples of using a php file as well as locally stored $lat and $lon variables.

L.drone is here: https://github.com/swordsteel/leaflet-drone

**Comment by perliedman** [comment]
Not sure about this, is this still an issue, or is it resolved by the code above?

As for your last comment, I'm not sure what you mean by "using a php file as well as locally stored $lat and $lon variables": the easiest way is to use the plugin is to load GeoJSON from an external resource, like a php file or whatever, but you can use other sources as well, like client side data, using the `update` method.

Will close this for now.
