### ISSUE TITLE
L.Realtime update with MarkerClusterGroup in L.Realtime container removes L.DomUtil classes for all L.Realtime markers and collapses expanded MarkerCluster.

### ISSUE THREAD

**Issue by maxrandolph** [perliedman/leaflet-realtime#112]
Hello,

Big fan of the library. Just noticed however that using L.Realtime in conjunction with L.MarkerCluster has an issue where if a MarkerCluster is expanded at the moment an L.Realtime update occurs, the expanded MarkerCluster will close, leading to a choppy experience. 

While not a huge deal, this also affects/wipes L.DomUtil customizations (e.g. css class for active marker selected) implemented on markers that are part of the MarkerClusters, effectively resetting and wiping any DOM class changes whenever L.Realtime updates. 

Perhaps a rare use case, but still tough to work around.

**Comment by claustres** [comment]
Yes interaction with others plugins is not completely transparent, for this use case you might have to keep track of all open clusters then reset it with [spiderfy()](https://github.com/Leaflet/Leaflet.markercluster#other-clusters-methods).

**Comment by perliedman** [comment]
Hi,
while I am certainly open to suggestions on how to improve this, I have a bit of a hard time seeing how Leaflet Realtime could improve this: as you might know, there is no special code in Leaflet Realtime to handle interaction with MarkerCluster; that is, Leaflet Realtime will just add features to the container it has been assigned. The container can be a `L.GeoJSON` (the default), a `MarkerClusterGroup` or whatever.

So, my understanding is that the problem rather lies on the MarkerCluster side, which apparently closes a cluster if it is updated. Not sure how that would best be addressed.

Again, I am open to suggestions on how to improve this in Leaflet Realtime, but until then I am going to close this issue.
