### ISSUE TITLE
How to get data

### ISSUE THREAD

**Issue by atkisai** [perliedman/leaflet-realtime#117]
I do not understand how to receive data. The documentation says that there are 3 ways to get data, but only one example is shown. How do I get data from variables, or is it impossible to do this? Can you at least a few examples?

**Comment by claustres** [comment]
There are already 2 samples with different approaches: https://github.com/perliedman/leaflet-realtime/blob/master/examples/earthquakes.js and https://github.com/perliedman/leaflet-realtime/blob/master/examples/trail.js. The third approach is to use `update(geoJson)/remove(geoJson)` methods to add/remove features.
