### ISSUE TITLE
Want to show my own geojson data..but fails

### ISSUE THREAD

**Issue by tomber42** [perliedman/leaflet-realtime#118]
Hi..

First..im not a developer.. so i try to adapt your example with wanderdrone to show the position of my gps tracker on a map. Its at the moment a locally html on my windows laptop. I use also the leaflet.provider plug in

Here is the code

    <!DOCTYPE html>
    <html>
    <head>
	
	<title>Halunke Position</title>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="shortcut icon" type="image/x-icon" href="docs/images/favicon.ico" />

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.3/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.3.3/dist/leaflet.js" integrity="sha512-tAGcCfR4Sc5ZP5ZoVz0quoZDYX5aCtEm/eu1KhSLj2c9eFrylXZknQYmxUssFaVJKvvc0dJQixhGjG2yXWiV9Q==" crossorigin=""></script>
    <script src="file:///C:temp/js/leaflet-providers.js"></script>
    <script src="file:///C:temp/js/leaflet-realtime.js"></script>
    </head>
    <body>
    <div id="mapid" style="width: 1000px; height: 800px;"></div>
    <script>
	var mymap = L.map('mapid');
	L.tileLayer.provider('Hydda.Full').addTo(mymap);
	realtime = L.realtime('http://axelcity.de/boot/position.txt', {
        interval: 3 * 1000,
        type: 'json'
    }).addTo(mymap);
    realtime.on('update', function() {
    mymap.fitBounds(realtime.getBounds(), {maxZoom: 7});
    });
    </script>
    </body>
    </html>

The geojson for my tracker (on my webserver axelcity.de) is a exact copy of the wanderdrone example, but static at the moment and with different coordinates

so http://axelcity.de/boot/position.txt is showing as {"geometry": {"type": "Point", "coordinates": [55.5, 13.90]}, "type": "Feature", "properties": {}}

This code doesn't work :(  I thought it will display the coordinates of my (static) geojson and then stay there

I also try to rename the position.txt in position.json but no difference

if i replace the source url in this code with https://wanderdrone.appspot.com every thing is ok and it will show the example

what i'm doing wrong?

Tomber

**Comment by perliedman** [comment]
Hi there!

Really hard to tell what the issue is without seeing running code.

If you haven't already, I would open the browser's developer tools and check for any errors.

If you're still stuck, try providing a link to a running example of your code.

**Comment by tomber42** [comment]
Thats was a good hint.. it was a missconfigured lighttpd server.. i had to add response header to the server configuration
"Access-Control-Allow-Origin" => "*",
"Access-Control-Expose-Headers" => "WWW-Authenticate",
"Access-Control-Allow-Headers" => "Authorization",
"Access-Control-Allow-Methods" => "POST, GET, OPTIONS"

Chrome developer tools said something about Access Control and no-cors , so after googling that i came to this solution.

Now it works :)
