### ISSUE TITLE
Change default marker

### ISSUE THREAD

**Issue by tomber42** [perliedman/leaflet-realtime#119]
Hi!

In the wanderdrohne example..if i would change the default marker..is this the right way to create an icon and give it to L.realtime layer? Because this did not work for me..

    <script>
      var red = L.icon({
      iconUrl: 'http://leafletjs.com/examples/custom-icons/leaf-red.png',
      iconSize: [30, 30]
    });

	var mymap = L.map('mapid');

	L.tileLayer.provider('Hydda.Full').addTo(mymap);
	
	
	realtime = L.realtime('https://wanderdrone.appspot.com', {
        interval: 8 * 1000,
        icon: red
  
      }).addTo(mymap);

    realtime.on('update', function() {
    mymap.fitBounds(realtime.getBounds(), {maxZoom: 13});
    
    });
	

    </script>

**Comment by perliedman** [comment]
Hi, you can use the `pointToLayer` option (from `L.GeoJSON`) to customize the marker. See #4.
