### ISSUE TITLE
Feature Request - Fading tail

### ISSUE THREAD

**Issue by dev-brother** [perliedman/leaflet-realtime#12]
Would be useful if the current position showed a trail of the past "n" positions set by the user. The benefit is to give an idea of direction. Currently on a slow or stopped object, one can't tell the general direction of travel. With a small tail, this would solve the problem nicely.

**Comment by perliedman** [comment]
This is a nice idea, but probably not functionality that would fit in to the plugin itself, but rather something that could be done as an example/tutorial.

Will keep this open and hope I or someone else (maybe you?) find the time to write such an example.

BTW, sorry about not responding before!

**Comment by perliedman** [comment]
Added an example for this in 7aa399562e14543a7fb56d21de76b2a18a697db8

**Comment by Snooper00** [comment]
Hi
Would it be possible to make the trail feature work with multiple points as well? 
Thanks
