### ISSUE TITLE
realtime don't update properties of geojson 

### ISSUE THREAD

**Issue by tomber42** [perliedman/leaflet-realtime#122]
Hi!
i use this code snippet to update my gps tracker data on map, everything working well besides that the geojson properties not being updated in the map.
 I show this properties with the OnEachFeature Option which called a function. This function creates a popup which shows the properties.

Now the problem..if the geojson is updated (position and properties) and the update is executed, only the position of the marker is updated, but not the properties in the popup. I have to reload the page to see the new properties.

How can i improve this?

```

 function onEachFeature(feature, layer) {
                if (feature.properties.course) {
                        popupContent = "Kurs: "+ feature.properties.course+" Grad <br>";
                }
                if (feature.properties.speed) {
                        popupContent += "Geschwindigkeit: "+ feature.properties.speed+" m/s <br>";
                }
                if (feature.properties.time) {
                        popupContent += "Zeit der GPS Daten: "+ feature.properties.time+"<br>";
                }
                layer.bindPopup(popupContent);
        }


 //initialisiere map
 var mymap = L.map('mapid');
 L.tileLayer.provider('Hydda.Full').addTo(mymap);
 realtime = L.realtime(('http://myurl/position.geojson'), {
        interval: 8 * 1000,

        pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, punktdef).bindTooltip("Tooltiptext");},

        onEachFeature: onEachFeature,

                                                                }).addTo(mymap);
 realtime.on('update', function() {
    mymap.fitBounds(realtime.getBounds(), {maxZoom: 15});
                               });
```
this is the position.geojson example
`{"properties": {"course": "87.0", "speed": "2.4", "time": "18:01:25 21.08.2018"}, "geometry": {"type": "Point", "coordinates": [18.578666632, 57.452197767]}, "type": "Feature"}
`

**Comment by perliedman** [comment]
Hi,

the marker is not re-created on each update, so your `onEachFeature` callback is only called the first time the feature is added to the map, not on later updates (since it's the same marker that is just moved).

So you need to bind a new popup to each marker in the `update` handler, something like:

```js
realtime.on('update', function(e) {
    Object.keys(e.enter).forEach(function(id) {
        var feature = e.enter[id];
        this.getLayer(id).bindPopup("Zeit der GPS Daten: "+ feature.properties.time+"<br>");
    });
}, this);
```

**Comment by tomber42** [comment]
Thank you for help.

Unfourtuanally this code does not work for me. It displays no popup.

**Comment by perliedman** [comment]
Yeah, forgot to `bind(this)` on the `forEach` function, I have updated the code.

**Comment by tomber42** [comment]
Hmm..even with your improved code i get:

leaflet-realtime.js:233 TypeError: this.getLayer is not a function
    at track.html:96
    at Array.forEach (<anonymous>)
    at track.html:94
    at e.fire (leaflet.js:5)
    at e._onNewData (leaflet-realtime.js:223)
    at e.<anonymous> (leaflet-realtime.js:91)
    at e.<anonymous> (leaflet-realtime.js:81) undefined

**Comment by perliedman** [comment]
Here's a running example of this functionality: https://plnkr.co/edit/7o3XELaRTnESSZaX5JGw?p=preview

I accidentally used `.enter` in my code above where I meant to use `.update`, but that doesn't explain the error you're seeing.

Try out the code from the link, it should work with some minor modifications.

**Comment by tomber42** [comment]
Thx, will try this

**Comment by tomber42** [comment]
Cool..it works... and so i could found the problem with your code above
 ```
 realtime.on('update', function(e) {
     Object.keys(e.enter).forEach(function(id) {
        var feature = e.enter[id];
        this.getLayer(id).bindPopup("Zeit der GPS Daten: "+ feature.properties.time+"<br>");
    }.bind(this));
 }, this);
```
the last "this" is wrong..if i remove that everything is ok
