### ISSUE TITLE
Cannot read property 'setContent' of undefined

### ISSUE THREAD

**Issue by cpcristian** [perliedman/leaflet-realtime#124]
Good afternoon.
in GeometryCollection(LineString) it generates the following error.

please help me.

`TypeError: Cannot read property 'setContent' of undefined
    at updateFeaturePopup ((index):186)
    at Array.forEach (<anonymous>)
    at NewClass.<anonymous> ((index):192)
    at NewClass.fire (leaflet-src.js:587)
    at NewClass._onNewData (leaflet-realtime.min.js:4)
    at NewClass.<anonymous> (leaflet-realtime.min.js:4)
    at NewClass.<anonymous> (leaflet-realtime.min.js:4) undefined`

`    circuit.on('update', function(e) {
      popupContent = function(fId) {
        var feature = e.features[fId],
        p = feature.properties;

        return `
          x  : ${p.x}  <br><br>
          x  : ${p.x}  <br>
          x  : ${p.x}  <br>
          x  : ${p.x}  <br>
        `
      },
      bindFeaturePopup = function(fId) {
        circuit.getLayer(fId).bindPopup(popupContent(fId));
      },
      updateFeaturePopup = function(fId) {
        circuit.getLayer(fId).getPopup().setContent(popupContent(fId));
      };

      circuit.getBounds();
      Object.keys(e.enter).forEach(bindFeaturePopup);
      Object.keys(e.update).forEach(updateFeaturePopup);`

**Comment by perliedman** [comment]
Hi,
it sounds like you are trying to `setContent` on a layer that does not have a popup (`getPopup()` returns undefined).

I would suggest stepping through the code in your browser's debugger to see what is happening. It is unfortunately not possible for me to tell without a running example, and also a bit outside the scope of this issue tracker if you do not believe this is a bug in Leaflet Realtime.
