### ISSUE TITLE
How keep zoom

### ISSUE THREAD

**Issue by steve007iii** [perliedman/leaflet-realtime#125]
`realtime.on('update', function() {
    map.fitBounds(realtime.getBounds(), {maxZoom: 3});
	
});`

When the zoom is updated in the site map, the new zoom is not updated and when the GeoJson load is updated it hits with this maxZoom: 3
I want to keep the zoom stable on the map site + - without being affected by the data update
How can I do this?

**Comment by perliedman** [comment]
Hi,
just remove the call to `fitBounds`, it's there explicitly for zooming in on the data. If you don't want it, just remove it.

**Comment by steve007iii** [comment]
Thank you very much.
I was making things difficult.

**Comment by deremuTVCode** [comment]
I have the same problem but it doesn't work with this solution.
