### ISSUE TITLE
old layer not being deleted

### ISSUE THREAD

**Issue by pedro-vicente** [perliedman/leaflet-realtime#126]
I have been using Leaflet to show static data using C++ web frameworks, like Wt, cutelyst, or QtWebApp, and it has been working perfectly.

My new app needs to show a Leaflet map in real time. This can be done from the server side, using HTTP server push or Server Sent Event (SSE),  but not all C++ frameworks support this well, particularly with JavaScript (and Leaflet).

So, I decided to give a try to  leaflet-realtime, where the update request comes the HTTP client (the web browser).

It works like a charm, but I have hit a trouble.
The goal is to update in real time a map at several locations with a marker and a circle, which radius is also generated every time.

This is the server side push version live demo made with Wt (every 20 seconds circles with random size are displayed)

http://www.eden-earth.org:9000/

Code here

https://github.com/pedro-vicente/wt

As can be seen , every time the map is re-loaded , which is slow and not visually pleasing.

So, the leaflet-realtime version , made with QtWebMap, avoids this

Code

https://github.com/pedro-vicente/qt_web_app/blob/master/map/src/map_handler.cc

The problem is that the OLD circles are not deleted, . the documentation says the old layer is removed .

Here is the code for the L.realtime generation. Apologies for the code being in C++.

```
void MapHandler::service_realtime(HttpResponse& response)
{
  QString body;
  std::ostringstream strm;
  strm
    << "<script>"
    << "var realtime = L.realtime('http://127.0.0.1:8080/', {"
    << "interval: 4 * 1000,"
    //add popup to default marker
    << "onEachFeature(f, l) {"
    << "  l.bindPopup(function() {"
    << "    return f.properties.id;"
    << "  });\n"
    //add circle
    << "  var circle = L.circle([38.9072, -77.0369], {"
    << "    color: '#ff0000',"
    << "    stroke: false,"
    << "    radius: f.properties.id"
    << "  }).addTo(map);"
    << " }\n"
    << "}).addTo(map);\n"
    << "realtime.on('update', function() {"
    << "map.fitBounds(realtime.getBounds(), {maxZoom: 13});"
    << "});"
    << "</script>";
  body += strm.str().c_str();
  qDebug() << body;
  response.write(strm.str().c_str());
}

```

**Comment by pedro-vicente** [comment]
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/6119070/48310280-a867ea80-e55a-11e8-8c14-2fffbffbb176.png">

**Comment by pedro-vicente** [comment]
the picture above shows the issue; there is a fetch every 4 seconds, but the circles are overwritten; the radius is random;

this is the code that generates the GeoJSON data

```
//To be able to figure out when new features are added, when old features are removed, 
    //and which features are just updated, Leaflet Realtime needs to identify each feature uniquely. 
    //This is done using a feature id. Usually, this can be done using one of the feature's properties.
    //By default, Leaflet Realtime will try to look for a called property id and use that.
    QString body;
    int r = rand() % 1000 + 1;
    std::ostringstream strm;
    strm
      << "{\"geometry\": {\"type\": \"Point\", \"coordinates\": [-77.0369, 38.9072]},"
      << "\"type\": \"Feature\", \"properties\": "
      << "{\"id\": \"";
    strm << std::to_string(r);
    strm
      << "\"}}";
    body += strm.str().c_str();
    qDebug() << body;
    response.write(strm.str().c_str());

```

**Comment by perliedman** [comment]
Hi, sorry for a late reply here.

The issue is that you are manually adding markers to the map in the `onEachFeature` callback, and these markers are not tracked by Leaflet Realtime since it can not know about them, which also makes them not remove from the map.

The trick is instead to create _both_ the circle and the marker in the `pointToLayer` callback, and add them to a `LayerGroup`.

I set up an example of this which you can check out: https://plnkr.co/edit/Beqqo2PiDDyC8NqmYGmZ?p=preview (please note I had to change the URL to make the example work from another domain - please do not rely on this URL working in the future :slightly_smiling_face: )

Hope this helps!

**Comment by pedro-vicente** [comment]
thanks, yes very helpful 

I updated the code

https://github.com/pedro-vicente/qt_web_app/blob/master/server_map/src/map_handler.cc

yes, I was adding a marker every time ; this could be detected if you kept the browser running for a long time, they were overwritten
