### ISSUE TITLE
Custom Marker

### ISSUE THREAD

**Issue by umsdavid** [perliedman/leaflet-realtime#130]
Hi,

I wanted to create a custom marker using pointlayer but failed. Here is my code:
Anyone can help? Thank you.

var realuser = L.realtime('datauser.json',
{
getFeatureId: function(f) { return f.properties.username; }
}).addTo(map);

realuser.on('update', function() {
interval: 2 * 1000
});

realuser.on('update', function(e) {
    Object.keys(e.enter).forEach(function(id) {
        var feature = e.enter[id];
        this.getLayer(id).bindPopup('<a href="userprofile.php">' + feature.properties.Name + '</a><br><b>' + feature.properties.Description + '</b>');
    }.bind(this));
});

**Comment by perliedman** [comment]
It is not clear to me what isn't working here, but it looks like you should use the `pointToLayer` or possibly `onEachFeature` option instead.
