### ISSUE TITLE
Online library http://www.liedman.net/leaflet-realtime/dist/leaflet-realtime.js

### ISSUE THREAD

**Issue by CiprianSavoiu** [perliedman/leaflet-realtime#137]
It is anything wrong with the link to the online version:
http://www.liedman.net/leaflet-realtime/dist/leaflet-realtime.js

Thank you.

Even the sample from plunker: http://embed.plnkr.co/wwd1Xk/ is not working anymore

**Comment by perliedman** [comment]
Thanks for notifying me. The `gh-pages` branch had for some reason been deleted from GitHub. It has been restored now.

For the built source, you are better off using a CDN like `unpkg.com` or similar.
