### ISSUE TITLE
Introduce addLayerToMap option

### ISSUE THREAD

**Issue by marcellangmaier** [perliedman/leaflet-realtime#141]
Hi
I am missing an option to prevent having the geojson leayer automatically added to the map. I want to let the user switch the layer via the layerswitch control.
Everything else works like a charm.

**Comment by perliedman** [comment]
Hi,
not sure I understand - Leaflet Realtime is itself a layer, you should add it or remove it from the map, not its wrapped GeoJSON layer.

**Comment by marcellangmaier** [comment]
Hi
I didn't realize that it's a layer, I was using the container option to let realtime update another layer. I will refactor my code.
Thanks a lot
