### ISSUE TITLE
Snap to road

### ISSUE THREAD

**Issue by wanmad** [perliedman/leaflet-realtime#142]
var map = L.map('map'),
    trail = {
        type: 'Feature',
        properties: {
            id: 1
        },
        geometry: {
            type: 'LineString',
            coordinates: []
        }
    },
	
    realtime = L.realtime(function(success, error) {
        L.Realtime.reqwest({
            url: 'geoJson.php',
            crossOrigin: true,
            type: 'json'
        })
        .then(function(data) {
            var trailCoords = trail.geometry.coordinates;
            trailCoords.push(data.geometry.coordinates);
			//console.log(trailCoords);
            //trailCoords.splice(0, Math.max(0, trailCoords.length - 5));
            success({
				
                type: 'FeatureCollection',
                features: [data, trail]
				
            });
        })
        .catch(error);
    }, {
        interval: 10 * 1000
    }).addTo(map);

how to make snap to road?

**Comment by perliedman** [comment]
You would either have to do it on the server, before the coordinates are sent to the client, or somehow snap the coordinates in the function that transforms to GeoJSON (the function in `then` above).

Exactly how to do it is unfortunately out of scope for this library.
