### ISSUE TITLE
Popup open automatically

### ISSUE THREAD

**Issue by wanmad** [perliedman/leaflet-realtime#143]
function createRealtimeLayer(url, container) {
    return L.realtime(url, {
        interval: 5 * 1000,
        getFeatureId: function(f) {
            return f.properties.url;
        },
        cache: true,
        container: container,
        onEachFeature(f, l) {
           l.bindPopup(function() {
                return '<b>Device:' + f.properties.name + '</b><br />' +
				    'Status:<b>' + f.properties.status+'</b><br />'+
					'Motion:<b>' + f.properties.motion+'</b><br />'+
                    'Last Update:' + f.properties.lastupdate +
					'<br>----------------------------------------<br/>'+
					'Location: '+ f.properties.location+
                    '<br/>Speed: <strong>' + f.properties.speed + '</strong>' +
					'<br/><strong>' + f.properties.add1 + '</strong>' +
					'<br/><strong>' + f.properties.add2 + '</strong>' +
					'<br/><strong>' + f.properties.add3 + '</strong>' +
                    '<br /><a href="' + f.properties.url + '">More information</a>';
            }, {autoClose:false}).openPopup();
        }
    });
}

var map = L.map('map'),
    clusterGroup = L.markerClusterGroup().addTo(map),
    subgroup1 = L.featureGroup.subGroup(clusterGroup),
    realtime1 = createRealtimeLayer('all.json.php', subgroup1).addTo(map);function 

how to open popup automatically after marker load without user click marker?

**Comment by perliedman** [comment]
Hi, sorry this is not a question specific to Leaflet Realtime but rather how to use Leaflet's popups. `openPopup` should work if I remember correctly, but apparently some detail is missing in your code. Sad to say, I do not have the time to debug code (I do this in my quite limited free time), so I am going to close this.
