### ISSUE TITLE
I try with my own geojson data but I see only one point

### ISSUE THREAD

**Issue by rmarzocchi84** [perliedman/leaflet-realtime#149]
Here an example http://demo.gter.it/demo_rfi/index.html trying my geojson data. 

it is practically the same of earthquakes example. If I use USGS geoJson it works, if I use my own data it seem to work but i see only one point while I want to see more points

I create data using an extraction from a Postgresql DB using a PHP script

**Comment by rmarzocchi84** [comment]
Here the php script used to generate geojson https://github.com/gtergeomatica/gnss_webgis_client/blob/master/geojson.php

Here the demo of PHP available: 
http://demo.gter.it/demo_rfi/geojson.php

I have already tested that the presence of "metadata" and "bbox" is not mandatory

**Comment by perliedman** [comment]
If you see only one point, it's most likely that they don't have a unique ID, or that you haven't configured the layer to pick up the correct ID property. See the docs for ’getFeatureId‘.

**Comment by rmarzocchi84** [comment]
Many thanks for your answer 

 I have a unique id. Which doc? (Sorry for my stupid question)

**Comment by rmarzocchi84** [comment]
Ok, sorry I understand... 

 getFeatureId: function(f) {
            return f.properties.url;
        },

f.properties.url; for my laye geojson is undefined 

f.id works well! 

I appreciate so much your suggestion!! All the best and nice plugin!
