### ISSUE TITLE
How to show result in linestring and with marker at every point ?

### ISSUE THREAD

**Issue by sakjain02** [perliedman/leaflet-realtime#155]
Can't get the source to change the linestring colour.

**Comment by perliedman** [comment]
Leaflet Realtime really only displays the GeoJSON you give it, so if you need to display a `LineString` and a set of `Marker`s, you would have to provide that GeoJSON. With a custom `source` function (described in the docs), you can easily convert a server response from a `LineString` to a `FeatureCollection` with the `LineString` as well as the `Marker`s.

Regarding `LineString` color, what have you tried? This should work if you provide a [`style`](https://leafletjs.com/reference-1.6.0.html#geojson-style) function or provide the [`onEachFeature`](https://leafletjs.com/reference-1.6.0.html#geojson-oneachfeature) option.

**Comment by sakjain02** [comment]
Thank you. But I solved the problem. I have used the realtime update feature to get the LineString by joining every point with matching colour.
