### ISSUE TITLE
Unable to move the map

### ISSUE THREAD

**Issue by TheSkripterDK** [perliedman/leaflet-realtime#159]
So its cool and all put how can i use it with mapbox satellite-streets-v9 tiles and while i try to move the map it now hovers back to the marker its tracking i want it to be tracking multiple markers and when they are within 5 meters of a specific leaflet point they will do x thing and be able to move the map around and searching and stuff :)
@perliedman

**Comment by TheSkripterDK** [comment]
@perliedman

**Comment by perliedman** [comment]
Remove or change the event handler for `update`, that's where the hover logic happens.
