### ISSUE TITLE
Ho to use existing marker?

### ISSUE THREAD

**Issue by VladimirKalachikhin** [perliedman/leaflet-realtime#166]
I want to use existing L.marker by some reasons.
My code:
```
var cursor = L.marker(startCenter, {
	'icon': GpsCursor,
});

var realtime = L.realtime(gpsAndDataServerURI, {
	interval: 1 * 1000,
	updateFeature:  function(feature,olgLayer,newLayer) {
		newLayer = cursor;	 
                newLayer.setLatLng( L.latLng(feature.geometry.coordinates[1], feature.geometry.coordinates[0]));
	},
}).addTo(map);
```
It works, but marker icon are default, not me custom.
This code:
```
var realtime = L.realtime(gpsanddataServerURI, {
	interval: 1 * 1000,
	pointToLayer: function (feature, latlng) {
		return cursor.setLatLng(latlng);
	}        
}).addTo(map);
```
work fine.

What am I doing wrong?

**Comment by perliedman** [comment]
Hi, it seems you have misunderstood the `updateFeature` option, it does not take a third argument, it is just called with two arguments. Also, the function should return the layer to be used, either `oldLayer` or a new instance that you create in `updateLayer`.
