### ISSUE TITLE
realtime is not a function - Angular 9 - ionic 5

### ISSUE THREAD

**Issue by yquintana** [perliedman/leaflet-realtime#168]
"leaflet": "^1.6.0",
    "leaflet-realtime": "^2.2.0",
    "leaflet-routing-machine": "^3.2.12",
     "@types/leaflet": "^1.5.12",
    "@types/leaflet-routing-machine": "^3.2.1"

import * as L from 'leaflet';
import   'leaflet-realtime';

**Comment by perliedman** [comment]
It sounds like Leaflet Realtime for some reason does not attach to the correct global `L`. With modern bundlers, this can happen in a few ways, but its hard to tell without seeing the actual code.

Having said that, this is not a problem with Leaflet Realtime itself, but rather with the build setup, so I am going to close this.
