### ISSUE TITLE
Add capability to display boat marker and other non-geoJSON types

### ISSUE THREAD

**Issue by shreyasbharath** [perliedman/leaflet-realtime#171]
Hi,

Thanks for creating an awesome library!

Just wondering if you ever considered adding support for non-geoJSON types like [boatmarker](https://github.com/thomasbrueggemann/leaflet.boatmarker)? I want to not only display points but also points with a compass heading.

Thanks for your help.

**Comment by perliedman** [comment]
You can do this by using the [`pointToLayer`](https://leafletjs.com/reference-1.6.0.html#geojson-pointtolayer) option, just like with Leaflet's GeoJSON layer.
