### ISSUE TITLE
 Feature data does not update in realtime

### ISSUE THREAD

**Issue by ecommerciando** [perliedman/leaflet-realtime#176]
Good evening, I have a problem with leaflet-realtime, updating the coordinates, the icon moves on the map, however if the values ​​in the properties on the map change and in the popup they do not change.
Ex.
The rotation of the marker does not change, speed data does not change. etc..

Here is the code I wrote:

`var map = L.map('map', {minZoom: 3, maxZoom: 18});
L.Control.measureControl().addTo(map);
mapLink = '<a href="http://www.esri.com/">Esri</a>';
wholink = 'i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community';
L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
    attribution: '&copy; '+mapLink+', '+wholink,
    maxZoom: 18,
}).addTo(map);

var shipLayer = L.layerGroup();

var realtime = L.realtime(
    {
    url: 'http://localhost/api/xxx/',
    crossOrigin: true,
    type: 'json',
    },
    {
    interval: 2 * 1000,
    getFeatureId: function(featureData){
    	return featureData.properties.idRisorsa;
    },
    pointToLayer: function (feature, latlng) {
      var track = L.icon({
        iconUrl: 'https://localhost' + feature.properties.TipoRisorsa + '.png',
        iconSize: [30, 30]
      });
      tracker = L.marker(latlng, {icon: track, rotationAngle: feature.properties.Angolo, title: feature.properties.NomePilota + " " + feature.properties.MarcaDrone} );
      tracker.bindPopup('Id: ' + feature.properties.idRisorsa +
                       '<br/>Angolo: ' + feature.properties.Angolo +
                       '<br/><strong>Nome:' + feature.properties.NomePilota +'</strong>' +
                       '<br/> Marca:' + feature.properties.MarcaDrone +
                       '<br/> Coordinate: ' + latlng);
      tracker.addTo(shipLayer);
      return tracker;
    }}).addTo(map);

realtime.on('update', function() {realtime.getBounds(), {maxZoom: 18};});
map.setView([0, 0], 0);
`

**Comment by omriasta** [comment]
Were you able to resolve this? I am seeing a similar issue where the color of my markers should change based on a feature in geojson but the colors will not change unless I refresh the entire page. The markers are in fact moving without refreshing the page but it looks like the color of the markers will not change.....
My code looks like this:

```
realtime = L.realtime(url, {
    interval: 60 * 1000,
    pointToLayer: function(feature, latlng) {
        if (feature.properties.pointtype == "vehicle" && feature.properties.Type == "BLS" && feature.properties.Status == "Busy") {
        return L.marker(latlng, {
            icon: icon(ambulance, "red"),
            title: feature.properties.Name
         
        }).bindTooltip(feature.properties.id, {
            permanent: true,
            direction: 'top'            
        });} if (feature.properties.pointtype == "vehicle" && feature.properties.Type == "BLS" && feature.properties.Status != "Busy") {
            return L.marker(latlng, {
                icon: icon(ambulance, "green"),
                title: feature.properties.Name
             
            }).bindTooltip(feature.properties.id, {
                permanent: true,
                direction: 'top'            
            });} 
            if (feature.properties.pointtype == "vehicle" && feature.properties.Type == "WheelChair" && feature.properties.Status == "Busy") {
                return L.marker(latlng, {
                    icon: icon(ambulette, "red"),
                    title: feature.properties.Name
                 
                }).bindTooltip(feature.properties.id, {
                    permanent: true,
                    direction: 'top'            
                });} if (feature.properties.pointtype == "vehicle" && feature.properties.Type == "WheelChair" && feature.properties.Status != "Busy") {
                    return L.marker(latlng, {
                        icon: icon(ambulette, "green"),
                        title: feature.properties.Name
                     
                    }).bindTooltip(feature.properties.id, {
                        permanent: true,
                        direction: 'top'            
                    });}
                    if (feature.properties.pointtype == "vehicle" && feature.properties.Type == "ALS" && feature.properties.Status == "Busy") {
                        return L.marker(latlng, {
                            icon: icon(ambulanceals, "red"),
                            title: feature.properties.Name
                         
                        }).bindTooltip(feature.properties.id, {
                            permanent: true,
                            direction: 'top'            
                        });} if (feature.properties.pointtype == "vehicle" && feature.properties.Type == "ALS" && feature.properties.Status != "Busy") {
                            return L.marker(latlng, {
                                icon: icon(ambulanceals, "green"),
                                title: feature.properties.Name
                             
                            }).bindTooltip(feature.properties.id, {
                                permanent: true,
                                direction: 'top'            
                            });}
        if (feature.properties.pointtype == "patient") {
            var title = [feature.properties.CallType, ' ',feature.properties.RunNumber.toString()].join('');
            return L.marker(latlng, {
            icon: icon(patient, "blue"),
            title: title
         
        }).bindTooltip(title, {
            permanent: true,
            direction: 'top'            
        });}
    }
}).addTo(map);
```

**Comment by AshleyVinning** [comment]
Does anyone have a workaround for this problem?

I'm trying to develop an ATC-like Radar screen, but features like the altitude and ground speed aren't updating.

Here is my code.

`
realtime = L.realtime({
    url: 'http://10.49.227.7/geojson_aircraft',
    crossOrigin: true,
    type: 'json'
}, {
    interval: 2.2 * 1000,
    pointToLayer: function (feature, latlng) {
		acvisible.push(feature.properties.id);
		if (typeof(achistory[feature.properties.id]) == "undefined") {
			achistory[feature.properties.id] = [];
		} else {
			achistory[feature.properties.id].push(latlng);
		}
		if (feature.properties.callsign == null) {
			feature.properties.callsign = '';
		}
		
		return L.marker(latlng, {icon: greenIcon}) .bindTooltip(feature.properties.callsign +
			'<br/>' + (feature.properties.altitude) + ' ft' +
			'<br/>' + (feature.properties.speed) + ' kts ' +
			'<br/>' , {direction: "right", permanent:true, listens:true, className: "aircraftLabel", fillOpacity: 1, opacity: 0.8, weight: 1  }).addTo(map);
    }                             
}).addTo(map);  

realtime.on('update', function(data) {
	for(var id in achistory) {
		if (achistory.hasOwnProperty(id)) {
			if (acvisible.indexOf(id)) {
				//console.log(achistory[id]);
				if (achistory[id].length == 1) {
					var polyline = L.polyline(achistory[id], {className: "aircraftLabel", dashArray: "5,5", fillOpacity: 0, opacity: 0.6, weight: 3, color: "green" }).addTo(map);
					polylines[id] = polyline;
				} 
				if (achistory[id].length > 1) {
					polylines[id].setLatLngs(achistory[id]);
				}
				achistory[id] = achistory[id].slice(-10);
			} else {
				delete achistory.id;
				delete polylines.id;
			}
		}
	}
});

`

**Comment by AshleyVinning** [comment]
Were you able to resolve this problem?

I'm experiencing it now with one of my projects.

Thanks,

Ashley

**Comment by omriasta** [comment]
It's been a while but I don't think it was resolved. I guess the only option would be to reload the page every once in a while....

**Comment by AshleyVinning** [comment]
Hi Omriasta.
That's a real shame. I've run out of ideas as so how to resolve this. Unfortunately refreshing the page wont work for my application. :/
If I ever come across an answer, I'll post it here.
Thanks for the response.

**Comment by perliedman** [comment]
The problem is that by default, marker options does not update, it only updates the position. There are several options to overcome this, depending on performance etc., but the easiest is probably:

```js
realtime = L.realtime(url, {
   // ...other options
   updateFeature: function() { return }
})
```

This will recreate the marker layers on each update, which does not give ideal peformance and prevents using CSS transitions etc, but it's a quick fix. You could also implement a more elaborate `updateFeature` function, [see the docs for `updateFeature`](https://github.com/perliedman/leaflet-realtime#-options).

**Comment by AshleyVinning** [comment]
Hi @perliedman, 

Thank you for your reply to this query.

I've tried multiple ways to get this to work, but have fallen flat I'm afraid.

Would you mind proofreading my work to see if you can figure out where updateFeature should go?

This produces a marker, which moves, but it doesn't update the marker's feature information.

```
realtime = L.realtime({
	url: 'http://127.0.0.1/geojson_aircraft',
    crossOrigin: true,
    type: 'json'
}, {
    interval: 5 * 100,
    pointToLayer: function (feature, latlng) {
		acvisible.push(feature.properties.id);
		if (typeof(achistory[feature.properties.id]) == "undefined") {
			achistory[feature.properties.id] = [];
		} else {
			achistory[feature.properties.id].push(latlng);
		}
		if (feature.properties.callsign == null) {
			feature.properties.callsign = '-';
		}
		return L.marker(latlng, {icon: greenIcon}).bindTooltip(feature.properties.callsign +
			'<br/>' + (feature.properties.altitude) + ' ft' +
			'<br/>' + (feature.properties.speed) + ' kts ' +
			'<br/>' , { permanent:true, className: "aircraftLabel", fillOpacity: 1, opacity: 0.8, weight: 1  }).addTo(map);
		}
}).addTo(map);  
```

Here is an icon shown moving on the map.

https://user-images.githubusercontent.com/73749996/199114210-2e699d04-61bf-4120-a262-76b6b6ee8da9.mov

Any help would be greatly appreciated.

Thanks,

Ash
