### ISSUE TITLE
Switch to using geometryToLayer

### ISSUE THREAD

**Issue by perliedman** [perliedman/leaflet-realtime#18]
As currently implemented, each update will create and add layers to the map for all incoming data, even if they often will immediately be removed again, since `updateFeature` will instead re-use the old layer.

It would be better to loop through incoming features and determine if we need to create new layers (with `geometryToLayer`), or if the existing layer can be updated. This would improved performance for larger datasets.

Not clear if this can be done in a backwards compatible way, so maybe for 2.0.

**Comment by kirantpatil** [comment]
:+1: , Sir any updates on this issue ?

**Comment by perliedman** [comment]
Sorry, I'm not actively working on this feature since it's not something I need right now.

Keeping this open to remind me if I get the time, or if someone else feels like implementing this change.
