### ISSUE TITLE
.css and .js files not online anymore?

### ISSUE THREAD

**Issue by jensvanhoof86** [perliedman/leaflet-realtime#191]
Hi, the following two files don't seem to be online anymore:

https://cdn.jsdelivr.net/leaflet-realtime/2.2/leaflet.realtime.css
https://cdn.jsdelivr.net/leaflet-realtime/2.2/leaflet.realtime.js

Where can they be sourced? Thanks!

**Comment by perliedman** [comment]
You can get the bundled JS file here: https://www.unpkg.com/browse/leaflet-realtime@2.2.0/dist/leaflet-realtime.js

Note sure about the CSS, I've been away from the project for a really long while, but don't think we've bundled a CSS?
