### ISSUE TITLE
Old minified version

### ISSUE THREAD

**Issue by siimots** [perliedman/leaflet-realtime#20]
Latest release is 1.2.0, but minified version states 1.1.0

`
/*! leaflet-realtime - v1.1.0 - 2016-02-04 */
`
https://github.com/perliedman/leaflet-realtime/blob/master/dist/leaflet-realtime.min.js#L1

**Comment by perliedman** [comment]
Wow! Thanks for catching and reporting this.

Since I already had an update in the pipe, I've pushed version 1.3.0 with correct dist files.

**Comment by siimots** [comment]
Thanks for update!

Works well in my site:
http://gis.ee/tallinn/
