### ISSUE TITLE
Trains demo not working

### ISSUE THREAD

**Issue by affleet** [perliedman/leaflet-realtime#27]
Hello there,

I have been trying to see the demo (http://www.liedman.net/leaflet-realtime/trains.html). It does not seem to be working here.
I do not see any moving objects. I checked the web-service with http://www.tagkartan.se/json/tag2.php, and it is returning data.
Please could you spare some time to look into this?

Kind regards

**Comment by perliedman** [comment]
Tågkartan has unfortunately removed its JSONP support, and it does not support CORS either, so there's currently no way to get the data, which is a shame since it was a pretty nice example on how to handle custom data.

I'm planning on removing the example, but haven't gotten around to it yet.

**Comment by affleet** [comment]
Thank you for the update.

Cheers!
