### ISSUE TITLE
To get the trains demo working

### ISSUE THREAD

**Issue by m-menon** [perliedman/leaflet-realtime#29]
I needed to check the trains demo to see how it works with multiple trackers. As it wasn't working I tried couple of things to get it working. For those keen to see the trains demo, there is a way. It just involves couple of steps

1. Host the script and the plugin on your server

2. Install this [chrome CORS extension](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) ( You can find something similar for Mozilla firefox too)

3. And change `type: 'jsonp'` to `type: 'json'` in `L.Realtime.reqwest` [example code](http://www.liedman.net/leaflet-realtime/trains.js)

And then the trains demo should work! After your tests remember to disable the CORS extension otherwise it may interfere with your other stuff. I had issues posting this solution with CORS ext enabled :-)

**Comment by perliedman** [comment]
That's an interesting workaround! However, I don't think relying on extensions and so on is a great way to illustrate the plugins functionality.

I've removed the train example, since the data isn't available through JSONP or CORS.
