### ISSUE TITLE
Can't change L.Realtime default marker icon?

### ISSUE THREAD

**Issue by fl4viu** [perliedman/leaflet-realtime#4]
Hi, it seems I can't change the default marker that comes with Leaflet when adding the layer to map. I tried setting a new icon using "pointToLayer" but with no result.

**Comment by perliedman** [comment]
Hi,
sorry for a really late reply.

Do you have any example code that shows the issue? I've been using `pointToLayer` without problems.

For example, I'm using this function to set marker icon depending on an external layer configuration:

```javascript
        pointToLayer: function(feature, latLng) {
            return L.marker(latLng, L.extend(layerConfig.markerOptions || {}, {
                icon: markerIcon
            }));
        }
```

**Comment by perliedman** [comment]
Closing this now.
