### ISSUE TITLE
How to use push model in leaflet realtime js api

### ISSUE THREAD

**Issue by bigbang4u2** [perliedman/leaflet-realtime#43]
On leaflet-realtime website the example is for pull model for realtime tracking of gps. There is an instruction that it can be used with push model. Is there any example for push model? Lets say I am getting stream of gps coordinates and I want to push them to leaflet realtime.

**Comment by perliedman** [comment]
This example shows how it can be done: https://github.com/perliedman/leaflet-realtime/blob/gh-pages/busses.js

Unfortunately, the bus API it uses doesn't work any longer, so you can't run it, but hopefully the code is enough to understand how push can be implemented.

**Comment by axelgunn** [comment]
Does the (not working) api return geoJson structure? I already have a socket service and intend to have it return the correct format and attributes such as point or multipoint etc. I was hoping you could fast-track me to the right format.

**Comment by perliedman** [comment]
@axelgunn no, in this case it returns data in another format that has to be transformed into GeoJSON before passing it along to the `success` callback. If you already get GeoJSON, you can just feed it directly to the callback.
