### ISSUE TITLE
How to make it work with linestrings

### ISSUE THREAD

**Issue by gloria-cho** [perliedman/leaflet-realtime#44]
Hi, perliedman!

Thank you for writing this code out! It worked with points, and maybe worked with polygons as well (didn't have real changing data to test this out, but at least the website is functioning and didn't break). However, when I wanted to auto-update some lines (from a separate geojson), the website broke. The geojson is "not well formed" according to Inspect Element -->Console, and that's how I know the website is updating (with the points and the polygons). Do you have any clues?

Thanks,
Gloria

**Comment by gloria-cho** [comment]
Got it. You have to create old layer (the original layer), and a new layer (the updating layer). Under the new layer, you need to add this below the getFreatureId (if you have it):

updateFeature: function(f, old_layer, new_layer) {
              if (f.geometry.type === 'LineString') {
                  return new_layer;
              }
          },

**Comment by perliedman** [comment]
Hi and thanks for notifying me!

This sounds like a bug, I'll try to investigate and possibly include a fix along the lines you suggest above.

**Comment by claustres** [comment]
On latest version managing line strings seems to work fine, however the [default implementation](https://github.com/perliedman/leaflet-realtime/blob/master/src/L.Realtime.js#L10) will recreate it on each update. If you'd like to simply update geometry you have to create a custom update method like this:
```js
updateFeature: function (feature, oldLayer) {
          const type = feature.geometry.type
          const coordinates = feature.geometry.coordinates
          // FIXME: support others geometry types ?
          switch (type) {
            case 'Point':
              oldLayer.setLatLng(L.GeoJSON.coordsToLatLngs(coordinates))
              break
            case 'LineString':
            case 'MultiLineString':
              oldLayer.setLatLngs(L.GeoJSON.coordsToLatLngs(coordinates, type === 'LineString' ? 0 : 1))
              break
            case 'Polygon':
            case 'MultiPolygon':
              oldLayer.setLatLngs(L.GeoJSON.coordsToLatLngs(coordinates, type === 'Polygon' ? 1 : 2))
              break
          }
          return oldLayer
}
```

**Comment by perliedman** [comment]
Thanks, @claustres ! I have added a slightly modified version of the `updateFeature` code you suggested above.
