### ISSUE TITLE
leaflet-routing-machine with leaflet-realtime

### ISSUE THREAD

**Issue by kirantpatil** [perliedman/leaflet-realtime#46]
Hi,

How to combine leaflet-realtime with leaflet-routing-machine  ?

Where Source Icon is moving on the route towards destination.

Any sample code is welcome.

Thanks.

**Comment by perliedman** [comment]
Hi,

there's nothing in particular about how to use LRM and Leaflet Realtime together, the to plugins are pretty much orthogonal. You can use them together, but there shouldn't be much need for integration, as far as I can see.

For updating a location of the device's location, you probably shouldn't even use Leaflet Realtime - it's easier to just code up something that moves a single marker every time a new geolocation is received.

**Comment by kirantpatil** [comment]
Sir. Thanks a lot for your help.
