### ISSUE TITLE
Trail -  Pass over the W180 line of longitude.

### ISSUE THREAD

**Issue by rohling** [perliedman/leaflet-realtime#47]
The exemple "trail.js",  when a trail straddles the W180 line of longitude, crossing from one side to the other, the trail does not continue on the other side of the W180 line, but is drawn back on the other side of the "current iteration" of the world. 
How to change it?

Thanks,

**Comment by perliedman** [comment]
We have to detect passing the date line and split the line into two lines at that point, interpolating it's latitude at the intersection of the dateline.

**Comment by perliedman** [comment]
I'm going to close this as it's not specific to Leaflet Realtime, but rather a problem with Leaflet's vector features when they cross the anti-meridian. There are some suggested solutions, but nothing definitive yet, but anyway it's not something that should be fixed in Leaflet Realtime.
