### ISSUE TITLE
How to add start - stop update control

### ISSUE THREAD

**Issue by rtfmfm** [perliedman/leaflet-realtime#53]
At first place, thank you for the great code, Sir!

I would like add start stop controls to the update. Can you show me an example of what is the best approach to do this.

Thank you in advance!

**Comment by perliedman** [comment]
You can use the `start` and `stop` methods. Please see the [API docs](https://github.com/perliedman/leaflet-realtime#methods).

**Comment by rtfmfm** [comment]
Thank you or the prompt reply! I read the API docs, but I'm new with JavaScript and can not manage it. Can you point me on an example, please.

Best regards!

**Comment by perliedman** [comment]
Sorry, I don't have an exampe at hand. You just call the `start`/`stop` method on the realtime layer you've created.
