### ISSUE TITLE
Memory explosion

### ISSUE THREAD

**Issue by kputland** [perliedman/leaflet-realtime#57]
My data contains ~4000 - ~5000 LineString, Memory balloons until browsers crash.

I have some profiling information (timeline and two heapsnapshot) from chrome (Version 55.0.2883.95 (64-bit)) on osx. Same experience with Safari and Firefox, but the three files are 165MB compressed and I'm unable to upload.

after ~1hr of updates the browser is consuming ~10GB memory.

updates interval is 30 seconds.

I'll work on sanitizing the sources and include tomorrow.

**Comment by perliedman** [comment]
Hi and sorry for not getting back to you sooner. I'd try to investigate with Chrome's devtools heap profiler, it can show quite clearly what's consuming all that memory and why.

Obviously, Leaflet or Leaflet Realtime is holding on to some layer it doesn't need, but it's hard to say without seeing the actual code. Do you happen to have a running example?

**Comment by kputland** [comment]
@perliedman Sorry, I don't have a working example anymore. I abandoned leaflet for the time being and did my work with the google maps api.
