### ISSUE TITLE
Only seing the last marker updating

### ISSUE THREAD

**Issue by axelgunn** [perliedman/leaflet-realtime#58]
Hi,

Below is a sample data I am using to update in realtime. My problem is that I only see the last marger on my map. My type is the "FeatureCollection" and I do not want to use "multipoint" because I need a setof features for each point. Can someone tell me what I am doing wrong here?

          ...  success({
                type: 'FeatureCollection',
                features: [data]
            });

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": "1",
      "properties": {
        "Name": "Worker1",
        "Status": "break"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -112.7171529,
          33.4954179
        ]
      }
    },
    {
      "type": "Feature",
      "id": "2",
      "properties": {
        "Name": "Worker2",
        "Status": "work"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -115.7171529,
          32.4954179
        ]
      }
    }
  ]
}

**Comment by perliedman** [comment]
By default, Leaflet Realtime will look for an `id` property in `properties`, not in the `Feature` itself. You need to pass a custom `getFeatureId` option:

```js
L.realtime(..., {
    // ...
    getFeatureId: function(f) {
        return f.id;
    }
});
```

Hope this helps!

**Comment by axelgunn** [comment]
Great. Problem solved. Thanks!
