### ISSUE TITLE
Multiple Markers

### ISSUE THREAD

**Issue by FoughtWon** [perliedman/leaflet-realtime#6]
Is it possible to pull from one server or servers to not just one marker being tracked but a lot more being tracked at the same time?

**Comment by FoughtWon** [comment]
If I keep instituting the it, will I be able to make more than one marker, or will I need a separate api for that?

**Comment by perliedman** [comment]
Yes, definitely.

To have more than one marker, you need to use the [`getFeatureId`](https://github.com/perliedman/leaflet-realtime#-options) option, to make it possible to track which object is which over multiple updates. 

To use more than one server, you can either create two or more separate `L.Realtime` layers (one per server), or you can provide a custom update function - see the docs on providing custom source function: https://github.com/perliedman/leaflet-realtime#-source.

**Comment by FoughtWon** [comment]
Ok thank you!
