### ISSUE TITLE
Removing and Re-adding a Marker

### ISSUE THREAD

**Issue by SegFault0x0** [perliedman/leaflet-realtime#62]
I have a collection of Features I'm passing in and would like to remove one of the markers based on a change in its status.  The remove function works in taking the marker off the screen, but if new data is received to recreate the marker with the same ID, it doesn't work.  It goes through the normal update procedure but won't recreate the icon.  After a `marker.setIcon(...)`, the `_icon` object is always "null".

Am I missing something, or am I not supposed to be able to remove and re-add the same ID without a page refresh?

**Comment by perliedman** [comment]
Can you provide some code that illustrates what you're doing?

Using `remove` should be ok, and the feature should be re-added on the next `update` if it's still in the data.

Just guessing from your comment, but you're not trying to re-use the same marker _instance_ after it's been removed? Leaflet Realtime will create a new instance when re-adding the feature to the map.

**Comment by SegFault0x0** [comment]
Here's a simplified version of my code.  Data is being pushed via a Socket.IO connection.  I'm currently testing the remove function with a client that pushes a Feature with the same 'myId' and a status of "Unknown," "Done," then "Unknown."  If "Done," the marker should be removed then re-created upon receiving the next Feature with a status of "Unknown."

**Sample JSON Object being sent:**
```
{
  'type': 'FeatureCollection',
  'features': [
    {
      geometry: {
        type: 'Point',
        coordinates: [
          -73.0000,
          37.0000
        ]
      },
      type: 'Feature',
      properties: {
        myId: '100',
        status: 'Unknown'
      }
    }
  ]
};
```

**index.html**
```javascript
var realtime = L.realtime(
  undefined, {
    // 'false' since I'm using Socket.IO to push data
    start: false,
    getFeatureId: function(feature) {
      return feature.properties.myId;
    },
    updateFeature: function(feat, oldLayer, newLayer) {
      if (feat.geometry.type === 'Point') {
        if (feat.properties.myId ===
          oldLayer.feature.properties.myId) {
          return oldLayer;
        }
      } else {
        return newLayer;
      }
    }
  }
).addTo(map);

socket.on('update', function(data) {
  var myData = JSON.parse(data);
  realtime.update(myData);
});

realtime.on('update', function(e) {
  var createMarker = function(fId) {
    var feature = e.features[fId];
    var marker = realtime.getLayer(fId);

    /* Excerpt from function call that changes icon color based on status */
    marker.status = feature.properties.status;
    marker.setIcon(new L.icon({
      iconUrl: color,
      iconSize: myIcon_Size,
      iconAnchor: myIcon_anchor,
      popupAnchor: myPopup_anchor,
    }));
    /********/
  };

  var updateMarker = function(fId) {
    var feature = e.features[fId];
    var marker = realtime.getLayer(fId);

    if (marker.status !== feature.properties.status) {
      /* Excerpt from function call that changes icon color based on status */
      marker.status = feature.properties.status;
      if (marker.status.toUppercase() === 'DONE') {
        realtime.remove(feature);
        return;
      } else { /* Change color accordingly */ }

      marker.setIcon(new L.icon({
        iconUrl: color,
        iconSize: myIcon_Size,
        iconAnchor: myIcon_anchor,
        popupAnchor: myPopup_anchor,
      }));
      /********/
    }
  };

  Object.keys(e.enter).forEach(createMarker);
  Object.keys(e.update).forEach(updateMarker);
});
```

**Comment by perliedman** [comment]
Ok, can't see any obvious problems with that code, although it's a bit complicated to say just from a quick look. I'll try to find some time to investigate, but can't promise anything.

A good idea would be for you to step through the removal and update process to see if you can spot anything weird.

**Comment by SegFault0x0** [comment]
No problem; I definitely appreciate any time you can find.  I've stepped through it a before and came up short but will take a second and third look and let you know anything I find.

**Comment by SegFault0x0** [comment]
@perliedman I found my error.  When I receive data from Socket.IO, I was only issuing an explicit call to `realtime.update` and trying to issue the `realtime.remove` call later (after I'd parsed properites.status at my convenience).

**Wrong**
```javascript
socket.on('update', function(data) {
  var myData = JSON.parse(data);
  realtime.update(myData);
});
```
I fixed it by checking my status immediately upon receipt of the data and calling `realtime.remove` on any features with a status of 'DONE'.

**Correct**
```javascript
socket.on('update', function(data) {
  var myData = JSON.parse(data);

  for (let i = 0, len = myData.features.length; i < len; ++i) {
    if (myData.features[i].properties.status.toUpperCase() === 'DONE') {
      realtime.remove(myData.features[i]);    // <-- remove() call
    } else {
      realtime.update(myData.features[i]);    // <-- Regular update() call
    }
  }
});
```
Now my test client can create an icon, remove it by changing its status to 'DONE', and recreate an icon with the same ID.  Thanks for taking a look, and great work on the plugin!

**Comment by perliedman** [comment]
@SegFault0x0 great to hear you sorted it out! I haven't used the "push" mode of the plugin much, so the docs are a bit thin on details.

**Comment by PeterPan73** [comment]
@perliedman @SegFault0x0 Hi, I use a similar method with socket but I have a problem with _removeMissing_ not working. As far as I understand manually adding with
`socket.on('update', function(data) {`
`var myData = JSON.parse(data);`
`realtime.update(myData);`
`});`
does not work with _removeMissing_ from [this ](https://github.com/perliedman/leaflet-realtime/issues/136#issuecomment-486970839)I also use _updateFeature_
For some reason I cannot use the @SegFault0x0 **Correct** code, because my logic is different.

Is it possible to use a socket and _removeMissing_ together?
