### ISSUE TITLE
Trying to persist Markers once the have been set

### ISSUE THREAD

**Issue by axelgunn** [perliedman/leaflet-realtime#63]
Hi 

I am having trouble using the update command. I have a varyating set of markers coming in via a service. On first interval I may get markers with ids 1,2,3,4, and on the second call I only receive f.ex. 3 and 4. My problem is that then markers 1 and 2 disappear. 

I am trying to persist the markers once they have been set or at least until I clear them manually. @perliedman you gave me the hint to use Update(), but I am not clever enough to make it happen.
Any bright minds out there that are willing to help?

reg. Axel

var map = new L.Map('map',
{
    crs: L.CRS.Simple,
    minZoom: -5,
    worldCopyJump: false,
    fullscreenControl: {
        pseudoFullscreen: false // if true, fullscreen to page width and height
    }

});

var bounds = [[0, 0], [18850, 16582]];
var image = L.imageOverlay('http://localhost:21074/uploads/floorplans/Intrazoffice_Office.svg', bounds).addTo(map);
map.fitBounds(bounds);

 var realtime = L.realtime(function (success, error) {
        L.Realtime.reqwest({
            url: 'http://localhost:21074/livedata/LiveFeed',
            crossOrigin: true,
            type: 'json'
        })
        .then(function (data) {
            success({
                type: 'FeatureCollection',
                features: [data]
            });
        })
         .catch(error);
        }, {
            interval: 3 * 1000,
            pointToLayer: function(feature, latlng) {
                return L.marker(latlng,
                {
                    icon: L.AwesomeMarkers.icon({
                        icon: 'shopping-cart',
                        prefix: 'fa',
                        markerColor: 'blue',
                        iconColor: 'white'
                    })
                });
            },
             onEachFeature: function(feature, layer) {
                 var content = '<p>' + feature.properties.typename + ': ' +
                     feature.properties.typelabel + '<br>Charge: ' +
                     feature.properties.batterylevel + '%' + 
                     '<\/p>';
                 layer.bindPopup(content);
         }
     }).addTo(map);

**Comment by SegFault0x0** [comment]
Where's your event listener for the update? (e.g. `realtime.on('update', function() {...}`)  Take a look at the example at [https://www.npmjs.com/package/leaflet-realtime#realtimeoptions](https://www.npmjs.com/package/leaflet-realtime#realtimeoptions) or try with the following code:

```javascript
realtime.on('update', function(e) {
  var updateLayer = function(fId) {
    var feature = e.features[fId];
    var layer = realtime.getLayer(fId);

    console.log('Feature #' + fId + ' battery level = ' + feature.properties.batterylevel); 
  };

  /**
   * Call the updateLayer() function on each layer.  You can also step through
   * the debugger on this iteration to ensure that your layers are being updated.
   */
  Object.keys(e.update).forEach(updateLayer);
});
