### ISSUE TITLE
Leaflet Realtime plugIn use with GeoJson

### ISSUE THREAD

**Issue by fray2388** [perliedman/leaflet-realtime#7]
I have a file GeoJSON "plaques.js" and I want you with leaflet realtime plugin (all markers simultaneously) spend. Can you help me?

here the geojson- file:

var plaques={"type":"FeatureCollection","features":[

{"type":"Feature","geometry":{"type":"Point","coordinates":[13.523563700000068,52.4909447]},"properties":{"plaqueid":"1","plaquedesc":"Berlin","colour":"","pc":"master"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[9.99368179999999,53.5510846]},"properties":{"plaqueid":"2","plaquedesc":"Hamburg","colour":"0","pc":"wn"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[11.581980599999952,48.1351253]},"properties":{"plaqueid":"3","plaquedesc":"Muenchen","colour":"128","pc":"wn"}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[8.682126700000026,50.1109221]},"properties":{"plaqueid":"4","plaquedesc":"Frankfurt am Main","colour":"-128","pc":"wn"}}
]}

**Comment by perliedman** [comment]
@fray2388 it looks like that file is not GeoJSON, but rather a JavaScript file that declares a variable that contains a GeoJSON object. This might sound like nitpicking, but the difference is that Leaflet Realtime can, out of the box, only work with raw GeoJSON; making it work with a js file containing GeoJSON will take a bit more work.

My suggestion is that you make `plaques.js` into `plaques.json` and remove the `var plaques = ` part. You will then be able to more or less copy the basic example from here: https://github.com/perliedman/leaflet-realtime/blob/master/examples/index.js

Hope this helps!

**Comment by fray2388** [comment]
@perliedman I tried to implement it, but it does not work for me (I think that I do not understand just a little).
I've done it so:
1. creates a GeoJSON file "plaques.json" with the following contents:
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          63.984375,
          61.938950426660604
        ]
      }
    }
  ]
}
2. In "Index.js" in the url "plaques.json" assigned:

var map = L.map('map'),
    realtime = L.realtime({
       url: 'plaques.json',
        crossOrigin: true,
        type: 'json'
    }, {
        interval: 3 * 1000
    }).addTo(map);

L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

realtime.on('update', function() {
    map.fitBounds(realtime.getBounds(), {maxZoom: 3});
})

3. when starting is nothing, just a gray layout with (+ I-) button above the left.


can you tell me how I leaflet-realtime use with a file.

**Comment by perliedman** [comment]
The file (`plaques.json` in your case) has to be accessible to the browser. Default security in browsers prevent loading JSON from the file system (you can't load JSON from `file://` URLs), so you have to serve the page, the JavaScript and the JSON over `http` (or `https`). If you haven't got a local web server already, I would recommend for example NPM's excellent module `http-server`, or Python's `SimpleHTTPServer`, but there are a lot of other solutions as well.

**Comment by fray2388** [comment]
@perliedman  I apologize that I ask so many questions and want to thank you for your help. now it works partially.
If I have more than one item is put on the map, just the last in the table.
```
{
   "type": "Feature Collection"
   "Features": [
     {
       "type": "Feature"
       "properties": {},
       "geometry": {
         "type": "Point"
         "coordinates": [
           50.9765625,
           60.413852350464914
         ]
       }
     },
     {
       "type": "Feature"
       "properties": {},
       "geometry": {
         "type": "Point"
         "coordinates": [
           14.0625,
           50.28933925329178
         ]
       }
     },
     {
       "type": "Feature"
       "properties": {},
       "geometry": {
         "type": "Point"
         "coordinates": [
           54.140625,
           48.922499263758255
         ]
       }
     }
   ]
}
```
Do you know how I make all 3 points for the same time on the map ???

**Comment by perliedman** [comment]
@fray2388 it's really mostly in the docs already - please read them carefully so that you understand them!

In this case, the answer is in the second paragraph of the [Overview](https://github.com/perliedman/leaflet-realtime#overview): you need to specify a way for Leaflet Realtime to identify you features.

By default, it uses a property called `id`, which you features are missing, which mean Leaflet Realtime will think they are all the same, with the identifier `undefined`.

You need to add an `id` property, or some other means, and tell Leaflet Realtime about it.

**Comment by fray2388** [comment]
OK has all worked out, thank you.
Can you help me maybe?
I now have 4 markers and one of them is a "Master PC" his and other 3 "worker node's" that are connected to a polyline .For this I added in GeoJSON at properties the "PC".
Tells you maybe how I can implement it?
```
{"type": "FeatureCollection", "features": [
    {"type": "Feature","properties": {"id":"1","name":"Berlin","wert":"","pc":"master"},"geometry": {"type": "Point","coordinates": [13.523563700000068,52.4909447]}},
    {"type": "Feature","properties": {"id":"2","name":"Hamburg","wert":"0","pc":"wn"},"geometry": {"type": "Point","coordinates": [9.99368179999999,53.5510846]}},
    {"type": "Feature","properties": {"id":"3","name":"München","wert":"128","pc":"wn"},"geometry": {"type": "Point","coordinates": [11.581980599999952,48.1351253]}},
    {"type": "Feature","properties": {"id":"4","name":"Frankfurt am Main","wert":"-128","pc":"wn"},"geometry": {"type": "Point","coordinates": [8.682126700000026,50.1109221]}}
	
 ]
}
```
