### ISSUE TITLE
Instructions to Run

### ISSUE THREAD

**Issue by aravindiiitb** [perliedman/leaflet-realtime#71]
Hi ,
I have downloaded the respository as a zip. 
How do you run it ? I just opened index.html

Can you please share the instruction to run it

Thanks

**Comment by perliedman** [comment]
Hi there,
the instructions on how to use this plugin is in [the README](https://github.com/perliedman/leaflet-realtime#example), and also an [online version of the Leaflet Realtime demo](http://www.liedman.net/leaflet-realtime).
