### ISSUE TITLE
examples index.html not working

### ISSUE THREAD

**Issue by GeorgeTSilva** [perliedman/leaflet-realtime#73]
I just tried to run the index.html in examples using Google Chrome on Windows 7 and it is not loading the basemap tiles nor the point marker.  trail.html seems to be working just fine though.

**Comment by perliedman** [comment]
Hm, just guessing, but it might be that the `dist` files are out of date. You can either build them yourself with `npm install`, or pull new ones from the repo since I updated them just now.

**Comment by GeorgeTSilva** [comment]
I just pulled the new files from the repo and the index.html example is now working.  Thanks!
