### ISSUE TITLE
how to use together with markerclusters?

### ISSUE THREAD

**Issue by erick-otenyo** [perliedman/leaflet-realtime#76]
I tried to add a L.realtime layer to a markercluster layer did not work.
Can it work together?

**Comment by spydmobile** [comment]
+1 as I am also trying to do this and have not been able to do it.

**Comment by perliedman** [comment]
Hi guys, I can't really say that this is something the plugin currently supports, unfortunately.

Leaflet Realtime is an extended GeoJSON layer, and MarkerCluster is another type of layer that assumes you add directly to it.

I guess it would be possible to restructure the plugin such that it could be used with other layer types, such as markercluster, but it's not something I have planned at the moment.

I would be open to discussing such a change if this is something you would be interested in taking on, or possibly if you would consider sponsoring development of it.

**Comment by spydmobile** [comment]
Understood. Thanks for responding so quickly.

**Comment by erick-otenyo** [comment]
Ok Thanks for the response.

**Comment by erick-otenyo** [comment]
Thanks @perliedman for the markerclusters compatibility, :+1:
