### ISSUE TITLE
Automatically start/stop when added to the map

### ISSUE THREAD

**Issue by andyclegg** [perliedman/leaflet-realtime#78]
To avoid unnecessary network requests, it would be nice if the start() and stop() methods could be called automatically when the layer is added to the map. I patched an older version of leaflet-realtime to do this by adding 'this.start()' in the onAdd handler, and 'this.stop()' in the onRemove handler, but I'm not sure how to go about reproducing this in the latest version.

**Comment by claustres** [comment]
Should be closed by https://github.com/perliedman/leaflet-realtime/pull/127.
