### ISSUE TITLE
Sending custom headers with request

### ISSUE THREAD

**Issue by anushanw** [perliedman/leaflet-realtime#79]
What I want to get done is to send a custom header (the access token) with the request when doing the following:

`realtime = L.realtime({
          url: 'myaddress/locations.json',
          crossOrigin: true,
          type: 'json'
      },`

How can this be done?

**Comment by jtm240** [comment]
I had the same problem and I found that the arguments to `realtime()` weren't being passed to fetch(). I submitted a PR which allows you to specify options `include: 'same-origin'` which will include cookies, or specify your own header. 

https://github.com/perliedman/leaflet-realtime/pull/83

**Comment by perliedman** [comment]
Fixed by merging #83.
