### ISSUE TITLE
Push Example

### ISSUE THREAD

**Issue by m-menon** [perliedman/leaflet-realtime#8]
firstly thanks a ton for the wonderful plugin. It has been really useful. But how would I get this to work with push? I mean when my MySQL database gets updated with data from a gps tracker, how can I push this to refresh and update the display? I am a little clueless as to how / where to implement the push. If you could give me some pointers it would be great.

Thanks once again for the great work,
M&M

**Comment by perliedman** [comment]
It depends very much on your server side, and less on the plugin itself.

To use push, you need some push protocol between the server and client. WebSockets is a popular technology, but there is also [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) that might work for you, and probably some other alternatives as well.

Given push input, you need to feed that input to leaflet-realtime's `update` and/or `remove` methods.

Hope this helps, and sorry for not getting back to you earlier.
