### ISSUE TITLE
Feature style control

### ISSUE THREAD

**Issue by devleaks** [perliedman/leaflet-realtime#81]
Hello,
You changed the base type for L.Realtime from L.GeoJSON to L.Layer.
In the process, I lost the [style property](http://leafletjs.com/reference-1.2.0.html#geojson-style).
How can I now style and control the change of style of features?
(I use L.Realtime to not only change positions (geometries) but also appearance (style) of features. It was working great, but broke when you change the base class of L.Realtime.)
Any suggestion for workaround? Thanks.

**Comment by devleaks** [comment]
Is it conceivable to propose L.Realtime as a mixin that could be _included_ to existing classes (L.Layer or L.GeoJSON) rather than extending a fixed class?

**Comment by perliedman** [comment]
Hi, thanks for reporting!

This is an oversight on my part, as you can see. I already have a special case to "borrow" the `onEachFeature` functionality from `GeoJSON`: https://github.com/perliedman/leaflet-realtime/blob/master/src/L.Realtime.js#L198

I imagine we would do the same for `styöe` (and possibly `filter`, don't know if that works properly now).

It's not likely I will find the time to do this right now, so any help here is appreciated.

Also: while your idea of using Realtime as a mixin is interesting and possibly very flexible, I think it has the downside of making the plugin more complicated to use/harder to understand. _Possibly_ we could make it as a mixin, but make a default layer that uses that mixin, that works exactly as it is today. Again, unfortunately not something I will have the time to look closer at right now.

**Comment by devleaks** [comment]
Does it make sense at all to inherit from Layer rather than GeoJSON? Your doc talks about features, GeoJSON, you are borrowing onEachFeature, I'm pretty sure that the fetch must return GeoJSON formatted feature(collection)... So it is GeoJSON all over the place. (Please have a look at the readme because it still talks about inheriting from L.GeoJSON.)
2.1 has a different "architecture" with that "container" layer. I will have a look at how it works and adjust my code if I can. In the meantime, I will stick with 2.0 which works like a charm!
So please give me a few hours to digest that new version. P.

**Comment by perliedman** [comment]
Yep, I specifically went to inheriting from `GeoJSON` to make the realtime layer be a _wrapper_ for another layer (by default `GeoJSON`), instead of being a specific layer type. This allows using Realtime together with, for example, MarkerCluster, which has been a feature request (#76).

However, GeoJSON is a very good default, and I did not want to break backwards compatibility, so hence porting `onEachFeature` etc.; but I forgot about `style`, so I accidentally broke backwards compatibility anyway.
