### ISSUE TITLE
How to replicate smooth movement of demo?

### ISSUE THREAD

**Issue by mbariola** [perliedman/leaflet-realtime#87]
Hello!
In your demo, I see the marker smoothly moving from one position to the next. 

In my implementation I included your code and the same data source (to test if I got it right), the marker teleports from one point to the other. (note the addition of awesomemarkers and modification to last line to not recalculate popup)

`
var realtime = L.realtime({

            url: 'https://wanderdrone.appspot.com/',
            crossOrigin: true,
            type: 'json'
        }, {
            interval: 2000,
        }).addTo(map);
```
realtime.on('update', function(e) {
    var coordPart = function(v, dirs) {
            return dirs.charAt(v >= 0 ? 0 : 1) +
                (Math.round(Math.abs(v) * 100) / 100).toString();
        },
        popupContent = function(fId) {
```

            var feature = e.features[fId],
                c = feature.geometry.coordinates;
            return 'Wander drone at ' +
                coordPart(c[1], 'NS') + ', ' + coordPart(c[0], 'EW');
        },
        bindFeaturePopup = function(fId) {
            var redMarker = L.AwesomeMarkers.icon({
                icon: 'star',
                markerColor: 'red',
                prefix: 'fa',
                spin: true
            });
            var l = realtime.getLayer(fId);
            //console.log('layer', l);
            l.setIcon(redMarker).bindPopup(popupContent(fId));
        },
        updateFeaturePopup = function(fId) {
            // won't be using
            realtime.getLayer(fId).getPopup().setContent(popupContent(fId));
        };

    map.fitBounds(realtime.getBounds(), {maxZoom: 3});

    Object.keys(e.enter).forEach(bindFeaturePopup);
    Object.keys(e.update);//.forEach(updateFeaturePopup);
});
`

I feel I am missing something but couldn't find what the difference is. Could you please point me in the right direction?

Thanks

**Comment by perliedman** [comment]
Hi, the smooth movement comes from a CSS `transition` effect, see here: https://github.com/perliedman/leaflet-realtime/blob/gh-pages/site.css#L9

You can probably extract that code directly, or make some minor modifications to fit your scenario.

**Comment by mbariola** [comment]
Awesome! works perfectly or should I say, smoothly now. thanks
