### ISSUE TITLE
JSON.parse: unexpected character

### ISSUE THREAD

**Issue by wuk986** [perliedman/leaflet-realtime#88]
I have dynamical geojson string created on the client side.
the string is valid and looks like this, but with more objects:
`{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[13.123719,47.909909999999995]},"properties":{"Number":"000","Plate":"x-xxxxx","Position":""}},{"type":"Feature","geometry":{"type":"Point","coordinates":[13.012451999999999,47.502575999999995]},"properties":{"Number":"000","Kennzeichen":"x-xxxxx","Position":""}}]}`

the string is stored in an `var` and this var is used  like this `url: var,`

but this doesn't work. I get the following error message:
> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data undefined  leaflet-realtime.min.js:4:3695

i also tried to load the string via ajax, but without success and now I am a little bit confused, what I am doing wrong.

has anybody an advice for me?
thx in advance

**Comment by perliedman** [comment]
This means you're somewhere feeding the system with invalid JSON data. The error message comes from `JSON.parse` when it can't parse the input string. So this is not a Leaflet Realtime problem, but rather a problem with the input data.

One way to debug this is to use devtools to stop on the error you copied above, and check the variables value. You can use for example https://jsonlint.com/ to verify your JSON. Hopefully, that way you can figure out why the JSON gets malformed.
