### ISSUE TITLE
setUrl() method fires an update with old URL

### ISSUE THREAD

**Issue by marianomd** [perliedman/leaflet-realtime#91]
The setUrl() method fires an ajax call with old URL instead of the new one.

**Comment by marianomd** [comment]
To solve it I changed the following code in initialize function:
```
if (this._url !== undefined) {
    src.url = this._url;
}
```
to this
```
if (this._url !== undefined) {
    url = src.url = this._url;
}
```

**Comment by perliedman** [comment]
Thanks for pointing this out!

I took a slightly different path and refactored some code to solve this, since I think the original way of handling this was a bit overly complex, which probably lead to this issue in the first place.
