### ISSUE TITLE
realtime for busses

### ISSUE THREAD

**Issue by mahoor-bhr** [perliedman/leaflet-realtime#98]
I saw this issue 'https://github.com/perliedman/leaflet-realtime/blob/gh-pages/busses.js' .how can i implement it by json files that contains Geojson data?json file is changed while user is walking.

what is in this url at the eventsource ?Is this geojson data?
var source = new EventSource('http://api.chab.us/buses/tail');

I tried Eventsource , by setting the url of the json file.but **NetworkError: 406 Not Acceptable**  occured.

please help me if possible.

**Comment by siimots** [comment]
You can view my example for buses with geojson: https://gis.ee/tallinn/

**Comment by perliedman** [comment]
@siimots wow, really cool site! Nice work.

**Comment by mahoor-bhr** [comment]
@siimots Tnx a lot for sharing this great sample.I'll try to change my code.

**Comment by mahoor-bhr** [comment]
Hi @siimots  .I tried to change my code as your sample.
I don't have tramm,Troll and buss layers ,and just have a json file that contains all info(as geojson) about location  of my users,like your peatused file.
But i achieve no success at the moving(updating) user locations in the map.

**Comment by siimots** [comment]
@mahoor-bhr, peatused.js static file which contains only stops. (Orange dots)
https://gis.ee/tallinn/geojson.php is used for updating tramm, troll, buss which are moving.
I think your problem might be that you don't have id in feature property.

features": [
{
"type": "Feature",
"properties": {
**"id": "96",**
"type": "3",
"line": "1",
"direction": "328"
}

id is needed for leaflet-realtime to know which one to update.
There are some other ways also, but having id property makes it work out of box.

**Comment by mahoor-bhr** [comment]
Hi @siimots  as you mentioned i was loaded my data in the peatused layer .I change my code to load in the tramm layer and now my problem has gone.

Thanks sir.

**Comment by vinayakkulkarni** [comment]
@siimots: you got source code for that?
